<?php

namespace Drupal\zero_entitywrapper\Content;

use Drupal;
use Drupal\zero_entitywrapper\Service\EntitywrapperService;
use Drupal\zero_preprocess\Collection\ProxyCollection;
use Drupal\zero_entitywrapper\Base\ContentWrapperInterface;

class ContentWrapperCollection extends ProxyCollection {

  private $service;
  private $unsafe;
  private bool $returnArray;

  /**
   * @param ContentWrapperInterface[] $array
   * @param array $unsafe
   * @param bool $returnArray return always an array after the first collection method
   */
  public function __construct($array = [], $unsafe = FALSE, bool $returnArray = FALSE) {
    parent::__construct($array);

    $this->returnArray = $returnArray;
    if ($unsafe) {
      $this->unsafe = $unsafe;
      $this->unsafe['info'] = $this->getService()->getBacktracerInfo($this->unsafe['caller'] ?? 0);
    }
  }

  /**
   * Set if the collection will return always an array after the first method
   * 
   * @param bool $returnArray
   * @return self
   */
  public function setReturnArray(bool $returnArray = TRUE): self {
    $this->returnArray = $returnArray;
    return $this;
  }

  /**
   * @return bool if the collection will return always an array after the first method
   */
  public function getReturnArray(): bool {
    return $this->returnArray;
  }

  public function getService(): EntitywrapperService {
    if ($this->service === NULL) {
      $this->service = Drupal::service('zero_entitywrapper.service');
    }
    return $this->service;
  }

  public function offsetSet($offset, $value): void {
    if ($value instanceof ContentWrapper) {
      throw new \InvalidArgumentException('Added item must be an ContentWrapper');
    }

    parent::offsetSet($offset, $value);
  }

  public function __call($name, $arguments) {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    $results = [];
    $is_array = FALSE;
    foreach ($this as $item) {
      if (method_exists($item, $name)) {
        $value = $item->{$name}(...$arguments);
        if ($value instanceof ProxyCollection) {
          foreach ($value as $value_item) {
            $results[] = $value_item;
          }
        } else {
          if (is_array($value)) $is_array = TRUE;
          $results[] = $value;
        }
      }
    }
    if ($is_array || $this->returnArray) {
      return $results;
    } else {
      return new self($results);
    }
  }

  public function array() {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>', 'Otherwise use cast to array <code>(array)</code>']);
    }
    return parent::array();
  }

  public function arrayCall(callable $array_function, ...$args) {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::arrayCall($array_function, ...$args);
  }

  public function itemCall(callable $array_function, ...$args) {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::itemCall($array_function, ...$args);
  }

  public function join($glue = ' ') {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::join($glue);
  }

  public function joinAsElement(string $element = 'div', string $attributes = '', string $glue = ''): ?string {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    if ($this->length() > 0) {
      $before = '<' . $element . ($attributes ? ' ' . $attributes : '') . '>';
      $after = '</' . $element . '>';
      return $before . $this->join($after . $glue . $before) . $after;
    } else {
      return NULL;
    }
  }

  public function map(callable $callback, ...$args): array {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::map($callback, $args); // TODO: Change the autogenerated stub
  }

  public function firstKey() {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::firstKey();
  }

  public function lastKey() {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::lastKey();
  }

  public function length() {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::length();
  }

  public function remove(int $offset, int $length = 1) {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::remove($offset, $length);
  }

  public function pushAt(int $offset, array $elements) {
    if ($this->unsafe) {
      $this->getService()->log('deprecation', $this->unsafe['message'], [...($this->unsafe['lines'] ?? []), 'Called in <code>' . $this->unsafe['info']['call'] . '</code>']);
    }
    return parent::pushAt($offset, $elements);
  }

}
