<?php

use Drupal\zero_wrapper_generator\Service\ZeroWrapperGeneratorService;

const ZERO_WRAPPER_GENERATOR__ENTITY_ROUTES = [
  'entity.paragraph.field_ui_fields',
  'entity.node.field_ui_fields',
];

/**
 * Implements hook_preprocess_HOOK().
 */
function zero_wrapper_generator_preprocess_page(&$vars) {
  if (in_array(Drupal::routeMatch()->getRouteName(), ZERO_WRAPPER_GENERATOR__ENTITY_ROUTES)) {
    /** @var ZeroWrapperGeneratorService $generator */
    $generator = \Drupal::service('zero_wrapper_generator.service');

    $vars['page']['content'] = [
      'generator_form' => $generator->getGenerateForm(Drupal::request()->get('entity_type_id'), Drupal::request()->get('bundle')),
    ] + $vars['page']['content'];
  }

  if (in_array(Drupal::routeMatch()->getRouteName(), ['entity.paragraphs_type.collection'])) {
    /** @var ZeroWrapperGeneratorService $generator */
    $generator = \Drupal::service('zero_wrapper_generator.service');

    $vars['page']['content'] = [
      'generator_form' => $generator->getAllGenerateForm('paragraph'),
    ] + $vars['page']['content'];
  }

  if (in_array(Drupal::routeMatch()->getRouteName(), ['entity.node_type.collection'])) {
    /** @var ZeroWrapperGeneratorService $generator */
    $generator = \Drupal::service('zero_wrapper_generator.service');

    $vars['page']['content'] = [
      'generator_form' => $generator->getAllGenerateForm('node'),
    ] + $vars['page']['content'];
  }
}
